#! /usr/bin/env perl

use strict;
use warnings;
use Test::More;
use FindBin;
use lib "$FindBin::Bin/lib";
use Test::DaemonProxy;

my $dp= Test::DaemonProxy->new;
$dp->run('--version');
$dp->response_like( qr/daemonproxy.*version/i, 'version message' );
$dp->response_like( qr/build timestamp: /i, 'build info' );
$dp->response_like( qr/git HEAD:/i, 'revision control info' );

# find source file with newest mtime, excluding autogenerated files
my $srcdir= "$FindBin::Bin/../src/";
my @files= grep { !($_ =~ /autogen/) && ($_ =~ /.[ch]$/) } <$srcdir/*>;
my ($newest)= reverse sort map { (stat $_)[9] } @files;

# Make sure the year of that file is included in the copyright range
my $year_of_newest= (localtime $newest)[5];
$dp->response_like( qr/copyright.*(\d\d\d\d)-(\d\d\d\d)/i, 'copyright' );
cmp_ok( $dp->last_captures->[1], '>=', $year_of_newest, 'includes year of newest file' );

$dp->response_like( qr/LICENSE/, 'ref to license file' );

$dp->exit_is( 1 );

done_testing;